copy COM\*.*              \ISAWIN\COM
copy TARGET\*.*           \ISAWIN\TARGET
copy TARGET\USER\*.*      \ISAWIN\TARGET\USER
copy TARGET\LIB\*.*       \ISAWIN\TARGET\LIB
copy TARGET\CMDS\*.*      \ISAWIN\TARGET\CMDS
copy TARGET\CMDS\isa16    \ISAWIN\TARGET\CMDS
copy TARGET\CMDS\isa11    \ISAWIN\TARGET\CMDS
